### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by zhangqinghua1008** [zhangjun001/FGNet#1]
你好哥们，我现在正复现你的算法。
目前infer是可以的，但是我想自行训练一个模型，而你数据生成的代码好像没有放到github上。
如果方便的话，可不可以把数据处理的代码上传一下？ 非常感谢~

**Comment by rongtongxueya** [comment]
请问你复现的时候有没有出现infer中的图片不能转化为float的这个错误啊，类似下面这种的
ValueError: could not convert string to float: '007.png'

**Comment by yonggangxiong** [comment]
> 
我也遇到了，请问该如何解决

**Comment by Lucaslifeday** [comment]
> 你复现的时候有没有出现推断中的图片不能变成float的这个错误啊，请类似下面的这种 ValueError: could not convert string to float: '007.png'

我也遇到了，请问如何解决呢

**Comment by zhangqinghua1008** [comment]
> 请问你复现的时候有没有出现infer中的图片不能转化为float的这个错误啊，类似下面这种的 ValueError: could not convert string to float: '007.png'

忘记了，反正最后复现的时候老报错，就没使用该模型作为对比算法。如果复现成功可以提供点建议，我也来用一下，哈哈

**Comment by HowardHuazy** [comment]
> 你好哥们，我现在正复现你的算法。
> 目前infer是可以的，但是我想自行训练一个模型，而你数据生成的代码好像没有放到github上。
> 如果方便的话，可不可以把数据处理的代码上传一下？ 非常感谢~

@zhangqinghua1008 您好，感谢您对我们论文的兴趣。
训练的话，需要设置一下这两个flag：
--train-path or ./train_process_files: a folder which the pipeline saves training visualization files to

--input-path or ./input_data: images used for inference or training. For our weakly supervised loss to work, the training images should be named as: AreaRatio_Uncertainty_.png.
For example, 0.4_0.05_.png means the target region occupies (40+/-5)% of the image.

我们的弱监督label在输入图片的文件名里，第一个数字是大约positive region占这张图片的比例，比如说40%，就是0.4； 第二个数字就是positive region在40%左右可能的浮动的区间，如果您觉得这张图的positive region大小大概占这张图的30-50%比例，第二个数字就是0.1 (10%), 当训练图片都重命名为类似 0.4_0.05_.png 这种格式后，放入指定的--input-path，就可以训练了。如果有其他问题欢迎指出

**Comment by HowardHuazy** [comment]
> 请问你复现的时候有没有出现infer中的图片不能转化为float的这个错误啊，类似下面这种的
> ValueError: could not convert string to float: '007.png'
@yonggangxiong 

您遇到的这个问题，应该是代码170行左右吗？
gt_percent = float(split_filename[0])
moe = float(split_filename[1])
这里我们的normal_loader尝试从图片名称里提取ground truth percent和margin of error, 就是文件名0.4_0.05_.png的第一个和第二个数字，来作为弱监督训练模型。如果此时文件名是007.jpg，代码可能就会报错了。

您在inference的时候，应该是不需要用到normal_loader(), 在323行，如果inference_path不为空，代码就会进入inference only mode，使用inference_loader(). inference_loader()和inference_dataset()没有parse input image name的操作，不需要输入image的固定名称格式，可以避免这个string to float error.
if args.inference_path is not None:
    dataset_loader = inference_loader()
    inference_mode = True

如果不是这个问题，可以麻烦您让我知道error是在第几行吗？谢谢

**Comment by Hw9712** [comment]
你好！请问finaledgegcncopy.py文件中怎么340、341行报错？

**Comment by HowardHuazy** [comment]
> 你好！请问finaledgegcncopy.py文件中怎么340、341行报错？

您好，half precision的配置比较复杂，可能有比较多的问题。建议您把arg-parser里的 --half-precision 设置为False
parser.add_argument('--half-precision', metavar='True or False', default=False, type=bool,
                    help='Half precision training, requires torch 0.4.0 and apex from nVidia')
